### ISSUE TITLE
How to create a new language

### ISSUE THREAD

**Issue by ghost** [joe-at-startupmedia/version-bump#2]
Describe the process of creating a new language

**Comment by ghost** [comment]
With the feature branch commit above, the following can be added to the .bump config file to parse markdown files:

```toml
[markdown]
enabled = true
```

If we wanted to match a markdown file that wasn't declared in the default settings we could explicitly override the settings by specifying the `files` property.

```toml
[markdown]
enabled = true
files = ['docs.md']
```
